// Ported from ./references/lazygit-master/pkg/gui/types/views.go

pub struct Views {
    pub status: View,
    pub submodules: View,
    pub files: View,
    pub branches: View,
    pub remotes: View,
    pub worktrees: View,
    pub tags: View,
    pub remote_branches: View,
    pub reflog_commits: View,
    pub commits: View,
    pub stash: View,
    pub main: View,
    pub secondary: View,
    pub staging: View,
    pub staging_secondary: View,
    pub patch_building: View,
    pub patch_building_secondary: View,
    pub merge_conflicts: View,
    pub options: View,
    pub confirmation: View,
    pub prompt: View,
    pub menu: View,
    pub commit_message: View,
    pub commit_description: View,
    pub commit_files: View,
    pub sub_commits: View,
    pub information: View,
    pub app_status: View,
    pub search: View,
    pub search_prefix: View,
    pub status_spacer1: View,
    pub status_spacer2: View,
    pub limit: View,
    pub suggestions: View,
    pub tooltip: View,
    pub extras: View,
    pub snake: View,
}

pub struct View;
