// Ported from ./references/lazygit-master/pkg/gui/presentation/icons/file_icons.go

use std::collections::HashMap;
use std::path::Path;
use std::sync::RwLock;

use super::IconProperties;

static DEFAULT_FILE_ICON: IconProperties = IconProperties::new("\uf15b", "#878787");
static DEFAULT_SUBMODULE_ICON: IconProperties = IconProperties::new("\u{f02a2}", "#FF4F00");
static DEFAULT_DIRECTORY_ICON: IconProperties = IconProperties::new("\uf07b", "#878787");

static NAME_ICON_MAP: &[(&str, IconProperties)] = &[
    (".atom", IconProperties::new("\ue764", "#EED9B7")),
    (".babelrc", IconProperties::new("\ue639", "#FED836")),
    (".bash_profile", IconProperties::new("\ue615", "#89E051")),
    (".bashprofile", IconProperties::new("\ue615", "#89E051")),
    (".bashrc", IconProperties::new("\ue795", "#89E051")),
    (".clang-format", IconProperties::new("\ue615", "#86806D")),
    (".clang-tidy", IconProperties::new("\ue615", "#86806D")),
    (".codespellrc", IconProperties::new("\u{f04c6}", "#35DA60")),
    (".condarc", IconProperties::new("\ue715", "#43B02A")),
    (".dockerignore", IconProperties::new("\u{f0868}", "#458EE6")),
    (".ds_store", IconProperties::new("\uf302", "#78919C")),
    (".editorconfig", IconProperties::new("\ue652", "#FFFFFF")),
    (".env", IconProperties::new("\u{f066a}", "#FBC02D")),
    (".eslintignore", IconProperties::new("\u{f0c7a}", "#3F52B5")),
    (".eslintrc", IconProperties::new("\u{f0c7a}", "#3F52B5")),
    (".git", IconProperties::new("\u{f02a2}", "#E64A19")),
    (".git-blame-ignore-revs", IconProperties::new("\u{f02a2}", "#E64A19")),
    (".gitattributes", IconProperties::new("\u{f02a2}", "#E64A19")),
    (".gitconfig", IconProperties::new("\u{f02a2}", "#E64A19")),
    (".github", IconProperties::new("\uf408", "#333333")),
    (".gitignore", IconProperties::new("\u{f02a2}", "#E64A19")),
    (".gitlab-ci.yml", IconProperties::new("\uf296", "#F54D27")),
    (".gitmodules", IconProperties::new("\u{f02a2}", "#E64A19")),
    (".gtkrc-2.0", IconProperties::new("\uf362", "#FFFFFF")),
    (".gvimrc", IconProperties::new("\ue62b", "#019833")),
    (".idea", IconProperties::new("\ue7b5", "#626262")),
    (".justfile", IconProperties::new("\uf0ad", "#6D8086")),
    (".luacheckrc", IconProperties::new("\ue615", "#868F9D")),
    (".luaurc", IconProperties::new("\ue615", "#00A2FF")),
    (".mailmap", IconProperties::new("\u{f01ee}", "#42A5F5")),
    (".nanorc", IconProperties::new("\ue838", "#440077")),
    (".npmignore", IconProperties::new("\ued0e", "#CC3837")),
    (".npmrc", IconProperties::new("\ued0e", "#CC3837")),
    (".nuxtrc", IconProperties::new("\u{f1106}", "#00C58E")),
    (".nvmrc", IconProperties::new("\ued0d", "#4CAF51")),
    (".pre-commit-config.yaml", IconProperties::new("\u{f06e2}", "#F8B424")),
    (".prettierignore", IconProperties::new("\ue6b4", "#4285F4")),
    (".prettierrc", IconProperties::new("\ue6b4", "#4285F4")),
    (".prettierrc.json", IconProperties::new("\ue6b4", "#4285F4")),
    (".prettierrc.json5", IconProperties::new("\ue6b4", "#4285F4")),
    (".prettierrc.toml", IconProperties::new("\ue6b4", "#4285F4")),
    (".prettierrc.yaml", IconProperties::new("\ue6b4", "#4285F4")),
    (".prettierrc.yml", IconProperties::new("\ue6b4", "#4285F4")),
    (".pylintrc", IconProperties::new("\ue615", "#968F6D")),
    (".rvm", IconProperties::new("\ue21e", "#D70000")),
    (".settings.json", IconProperties::new("\ue70c", "#854CC7")),
    (".SRCINFO", IconProperties::new("\uf129", "#0F94D2")),
    (".tmux.conf", IconProperties::new("\uebc8", "#14BA19")),
    (".tmux.conf.local", IconProperties::new("\uebc8", "#14BA19")),
    (".Trash", IconProperties::new("\uf1f8", "#ACBCEF")),
    (".vimrc", IconProperties::new("\ue62b", "#019833")),
    (".vscode", IconProperties::new("\ue70c", "#007ACC")),
    (".Xauthority", IconProperties::new("\uf369", "#E54D18")),
    (".Xresources", IconProperties::new("\uf369", "#E54D18")),
    (".xinitrc", IconProperties::new("\uf369", "#E54D18")),
    (".xsession", IconProperties::new("\uf369", "#E54D18")),
    (".zprofile", IconProperties::new("\ue615", "#89E051")),
    (".zshenv", IconProperties::new("\ue615", "#89E051")),
    (".zshrc", IconProperties::new("\ue795", "#89E051")),
    ("_gvimrc", IconProperties::new("\ue62b", "#019833")),
    ("_vimrc", IconProperties::new("\ue62b", "#019833")),
    ("AUTHORS", IconProperties::new("\uedca", "#A172FF")),
    ("AUTHORS.txt", IconProperties::new("\uedca", "#A172FF")),
    ("bin", IconProperties::new("\u{f12a7}", "#25A79A")),
    ("brewfile", IconProperties::new("\ue791", "#701516")),
    ("bspwmrc", IconProperties::new("\uf355", "#2F2F2F")),
    ("BUILD", IconProperties::new("\ue63a", "#89E051")),
    ("build.gradle", IconProperties::new("\ue660", "#005F87")),
    ("build.zig.zon", IconProperties::new("\ue6a9", "#F69A1B")),
    ("bun.lockb", IconProperties::new("\ue76f", "#EADCD1")),
    ("cantorrc", IconProperties::new("\uf373", "#1C99F3")),
    ("Cargo.lock", IconProperties::new("\ue7a8", "#DEA584")),
    ("Cargo.toml", IconProperties::new("\ue7a8", "#DEA584")),
    ("checkhealth", IconProperties::new("\u{f04d9}", "#75B4FB")),
    ("CMakeLists.txt", IconProperties::new("\ue794", "#DCE3EB")),
    ("CODE_OF_CONDUCT", IconProperties::new("\uf4ae", "#E41662")),
    ("CODE_OF_CONDUCT.md", IconProperties::new("\uf4ae", "#E41662")),
    ("CODE-OF-CONDUCT.md", IconProperties::new("\uf4ae", "#E41662")),
    ("commit_editmsg", IconProperties::new("\ue702", "#F54D27")),
    ("COMMIT_EDITMSG", IconProperties::new("\ue702", "#E54D18")),
    ("commitlint.config.js", IconProperties::new("\u{f0718}", "#039688")),
    ("commitlint.config.ts", IconProperties::new("\u{f0718}", "#039688")),
    ("compose.yaml", IconProperties::new("\uf21f", "#0088C9")),
    ("compose.yml", IconProperties::new("\uf21f", "#0088C9")),
    ("config", IconProperties::new("\uf013", "#696969")),
    ("containerfile", IconProperties::new("\uf21f", "#0088C9")),
    ("copying", IconProperties::new("\u{f0124}", "#FF5821")),
    ("copying.lesser", IconProperties::new("\ue60a", "#CBCB41")),
    ("docker-compose.yaml", IconProperties::new("\uf21f", "#0088C9")),
    ("docker-compose.yml", IconProperties::new("\uf21f", "#0088C9")),
    ("dockerfile", IconProperties::new("\uf21f", "#0088C9")),
    ("Dockerfile", IconProperties::new("\uf308", "#458EE6")),
    ("ds_store", IconProperties::new("\uf179", "#DDDDDD")),
    ("eslint.config.cjs", IconProperties::new("\u{f0c7a}", "#3F52B5")),
    ("eslint.config.js", IconProperties::new("\u{f0c7a}", "#3F52B5")),
    ("eslint.config.mjs", IconProperties::new("\u{f0c7a}", "#3F52B5")),
    ("eslint.config.ts", IconProperties::new("\u{f0c7a}", "#3F52B5")),
    ("ext_typoscript_setup.txt", IconProperties::new("\ue772", "#FF8700")),
    ("favicon.ico", IconProperties::new("\ue623", "#CBCB41")),
    ("fp-info-cache", IconProperties::new("\uf34c", "#FFFFFF")),
    ("fp-lib-table", IconProperties::new("\uf34c", "#FFFFFF")),
    ("FreeCAD.conf", IconProperties::new("\uf336", "#CB333B")),
    ("gemfile$", IconProperties::new("\ue791", "#701516")),
    ("gitignore_global", IconProperties::new("\u{f02a2}", "#E64A19")),
    ("gnumakefile", IconProperties::new("\ueba2", "#EF5351")),
    ("GNUmakefile", IconProperties::new("\ue779", "#6D8086")),
    ("go.mod", IconProperties::new("\ue627", "#02ACC1")),
    ("go.sum", IconProperties::new("\ue627", "#02ACC1")),
    ("go.work", IconProperties::new("\ue627", "#02ACC1")),
    ("gradle", IconProperties::new("\ue660", "#005F87")),
    ("gradle-wrapper.properties", IconProperties::new("\ue660", "#005F87")),
    ("gradle.properties", IconProperties::new("\ue660", "#005F87")),
    ("gradlew", IconProperties::new("\ue660", "#005F87")),
    ("gruntfile.babel.js", IconProperties::new("\ue611", "#E37933")),
    ("gruntfile.coffee", IconProperties::new("\ue611", "#E37933")),
    ("gruntfile.js", IconProperties::new("\ue611", "#E37933")),
    ("gruntfile.ls", IconProperties::new("\ue611", "#E37933")),
    ("gruntfile.ts", IconProperties::new("\ue611", "#E37933")),
    ("gtkrc", IconProperties::new("\uf362", "#FFFFFF")),
    ("gulpfile.babel.js", IconProperties::new("\ue610", "#CC3E44")),
    ("gulpfile.coffee", IconProperties::new("\ue610", "#CC3E44")),
    ("gulpfile.js", IconProperties::new("\ue610", "#CC3E44")),
    ("gulpfile.ls", IconProperties::new("\ue610", "#CC3E44")),
    ("gulpfile.ts", IconProperties::new("\ue610", "#CC3E44")),
    ("hidden", IconProperties::new("\uf023", "#555555")),
    ("hypridle.conf", IconProperties::new("\uf359", "#00AAAE")),
    ("hyprland.conf", IconProperties::new("\uf359", "#00AAAE")),
    ("hyprlock.conf", IconProperties::new("\uf359", "#00AAAE")),
    ("hyprpaper.conf", IconProperties::new("\uf359", "#00AAAE")),
    ("i3blocks.conf", IconProperties::new("\uf35a", "#E8EBEE")),
    ("i3status.conf", IconProperties::new("\uf35a", "#E8EBEE")),
    ("include", IconProperties::new("\ue5fc", "#EEEEEE")),
    ("index.theme", IconProperties::new("\uee72", "#2DB96F")),
    ("ionic.config.json", IconProperties::new("\ue66b", "#508FF7")),
    ("justfile", IconProperties::new("\uf0ad", "#6D8086")),
    ("kalgebrarc", IconProperties::new("\uf373", "#1C99F3")),
    ("kdeglobals", IconProperties::new("\uf373", "#1C99F3")),
    ("kdenlive-layoutsrc", IconProperties::new("\uf33c", "#83B8F2")),
    ("kdenliverc", IconProperties::new("\uf33c", "#83B8F2")),
    ("kritadisplayrc", IconProperties::new("\uf33d", "#F245FB")),
    ("kritarc", IconProperties::new("\uf33d", "#F245FB")),
    ("lib", IconProperties::new("\u{f1517}", "#8BC34A")),
    ("LICENSE", IconProperties::new("\uf02d", "#EDEDED")),
    ("LICENSE.md", IconProperties::new("\uf02d", "#EDEDED")),
    ("localized", IconProperties::new("\uf179", "#DDDDDD")),
    ("lxde-rc.xml", IconProperties::new("\uf363", "#909090")),
    ("lxqt.conf", IconProperties::new("\uf364", "#0192D3")),
    ("Makefile", IconProperties::new("\ue673", "#FEFEFE")),
    ("mix.lock", IconProperties::new("\ue62d", "#A074C4")),
    ("mpv.conf", IconProperties::new("\uf36e", "#3B1342")),
    ("node_modules", IconProperties::new("\ue718", "#E8274B")),
    ("npmignore", IconProperties::new("\ue71e", "#E8274B")),
    ("nuxt.config.cjs", IconProperties::new("\u{f1106}", "#00C58E")),
    ("nuxt.config.js", IconProperties::new("\u{f1106}", "#00C58E")),
    ("nuxt.config.mjs", IconProperties::new("\u{f1106}", "#00C58E")),
    ("nuxt.config.ts", IconProperties::new("\u{f1106}", "#00C58E")),
    ("package-lock.json", IconProperties::new("\ued0d", "#F54436")),
    ("package.json", IconProperties::new("\ued0d", "#4CAF51")),
    ("PKGBUILD", IconProperties::new("\uf303", "#0F94D2")),
    ("platformio.ini", IconProperties::new("\ue682", "#F6822B")),
    ("pom.xml", IconProperties::new("\u{f06d3}", "#FF7043")),
    ("prettier.config.cjs", IconProperties::new("\ue6b4", "#4285F4")),
    ("prettier.config.js", IconProperties::new("\ue6b4", "#4285F4")),
    ("prettier.config.mjs", IconProperties::new("\ue6b4", "#4285F4")),
    ("prettier.config.ts", IconProperties::new("\ue6b4", "#4285F4")),
    ("PrusaSlicer.ini", IconProperties::new("\uf351", "#EC6B23")),
    ("PrusaSlicerGcodeViewer.ini", IconProperties::new("\uf351", "#EC6B23")),
    ("py.typed", IconProperties::new("\ue606", "#ffbc03")),
    ("QtProject.conf", IconProperties::new("\uf375", "#40CD52")),
    ("R", IconProperties::new("\u{f07d4}", "#2266BA")),
    ("README", IconProperties::new("\u{f00ba}", "#EDEDED")),
    ("README.md", IconProperties::new("\u{f00ba}", "#EDEDED")),
    ("robots.txt", IconProperties::new("\u{f06a9}", "#5D7096")),
    ("rubydoc", IconProperties::new("\ue73b", "#F32C24")),
    ("SECURITY", IconProperties::new("\u{f0483}", "#BEC4C9")),
    ("SECURITY.md", IconProperties::new("\u{f0483}", "#BEC4C9")),
    ("settings.gradle", IconProperties::new("\ue660", "#005F87")),
    ("svelte.config.js", IconProperties::new("\ue697", "#FF5821")),
    ("sxhkdrc", IconProperties::new("\uf355", "#2F2F2F")),
    ("sym-lib-table", IconProperties::new("\uf34c", "#FFFFFF")),
    ("tailwind.config.js", IconProperties::new("\u{f13ff}", "#4DB6AC")),
    ("tailwind.config.mjs", IconProperties::new("\u{f13ff}", "#4DB6AC")),
    ("tailwind.config.ts", IconProperties::new("\u{f13ff}", "#4DB6AC")),
    ("tmux.conf", IconProperties::new("\uebc8", "#14BA19")),
    ("tmux.conf.local", IconProperties::new("\uebc8", "#14BA19")),
    ("tsconfig.json", IconProperties::new("\ue628", "#0188D1")),
    ("unlicense", IconProperties::new("\ue60a", "#D0BF41")),
    ("vagrantfile$", IconProperties::new("\uf2b8", "#1868F2")),
    ("vlcrc", IconProperties::new("\u{f057c}", "#E85E00")),
    ("webpack", IconProperties::new("\u{f072b}", "#519ABA")),
    ("weston.ini", IconProperties::new("\uf367", "#FFBB01")),
    ("WORKSPACE", IconProperties::new("\ue63a", "#89E051")),
    ("WORKSPACE.bzlmod", IconProperties::new("\ue63a", "#89E051")),
    ("xmobarrc", IconProperties::new("\uf35e", "#FD4D5D")),
    ("xmobarrc.hs", IconProperties::new("\uf35e", "#FD4D5D")),
    ("xmonad.hs", IconProperties::new("\uf35e", "#FD4D5D")),
    ("xorg.conf", IconProperties::new("\uf369", "#E54D18")),
    ("xsettingsd.conf", IconProperties::new("\uf369", "#E54D18")),
    ("yarn.lock", IconProperties::new("\ue6a7", "#0188D1")),
];

static EXT_ICON_MAP: &[(&str, IconProperties)] = &[
    (".3gp", IconProperties::new("\uf03d", "#F6822B")),
    (".3mf", IconProperties::new("\u{f01a7}", "#888888")),
    (".7z", IconProperties::new("\uf410", "#ECA517")),
    (".DS_store", IconProperties::new("\uf179", "#A2AAAD")),
    (".a", IconProperties::new("\u{f1517}", "#8BC34A")),
    (".aac", IconProperties::new("\uf001", "#20C2E3")),
    (".adb", IconProperties::new("\ue6b5", "#22FFFF")),
    (".ads", IconProperties::new("\ue6b5", "#22FFFF")),
    (".ai", IconProperties::new("\ue7b4", "#D0BF41")),
    (".aif", IconProperties::new("\uf001", "#00AFFF")),
    (".aiff", IconProperties::new("\u{f0386}", "#EE534F")),
    (".android", IconProperties::new("\ue70e", "#66AF3D")),
    (".ape", IconProperties::new("\uf001", "#00AFFF")),
    (".apk", IconProperties::new("\ue70e", "#8BC34A")),
    (".app", IconProperties::new("\ueae8", "#9F0500")),
    (".apple", IconProperties::new("\ue635", "#A2AAAD")),
    (".applescript", IconProperties::new("\uf302", "#78919C")),
    (".asc", IconProperties::new("\u{f0306}", "#25A79A")),
    (".asm", IconProperties::new("\ue637", "#0091BD")),
    (".ass", IconProperties::new("\u{f0a16}", "#FFB713")),
    (".astro", IconProperties::new("\ue6b3", "#FF6D00")),
    (".avi", IconProperties::new("\u{f0381}", "#FF9800")),
    (".avif", IconProperties::new("\u{f021f}", "#25A6A0")),
    (".avro", IconProperties::new("\ue60b", "#965824")),
    (".awk", IconProperties::new("\u{f018d}", "#FF7043")),
    (".azcli", IconProperties::new("\uebd8", "#2088E5")),
    (".bak", IconProperties::new("\u{f006f}", "#6D8086")),
    (".bash", IconProperties::new("\uebca", "#FF7043")),
    (".bash_history", IconProperties::new("\ue795", "#8DC149")),
    (".bash_profile", IconProperties::new("\ue795", "#8DC149")),
    (".bashrc", IconProperties::new("\ue795", "#8DC149")),
    (".bat", IconProperties::new("\u{f018d}", "#FF7043")),
    (".bats", IconProperties::new("\u{f0b5f}", "#D2D2D2")),
    (".bazel", IconProperties::new("\ue63a", "#44A047")),
    (".bib", IconProperties::new("\u{f1517}", "#8BC34A")),
    (".bicep", IconProperties::new("\u{f0fd7}", "#FBC02D")),
    (".bicepparam", IconProperties::new("\ue63b", "#797DAC")),
    (".blade.php", IconProperties::new("\uf2f7", "#FF5252")),
    (".blend", IconProperties::new("\u{f00ab}", "#ED8F30")),
    (".blp", IconProperties::new("\u{f0ebe}", "#458EE6")),
    (".bmp", IconProperties::new("\u{f021f}", "#25A6A0")),
    (".brep", IconProperties::new("\u{f0eeb}", "#839463")),
    (".bz", IconProperties::new("\uf410", "#ECA517")),
    (".bz2", IconProperties::new("\uf410", "#ECA517")),
    (".bz3", IconProperties::new("\uf410", "#ECA517")),
    (".bzl", IconProperties::new("\ue63a", "#44A047")),
    (".c", IconProperties::new("\ue61e", "#0188D1")),
    (".c++", IconProperties::new("\ue61d", "#0188D1")),
    (".cab", IconProperties::new("\ue70f", "#626262")),
    (".cache", IconProperties::new("\uf49b", "#FFFFFF")),
    (".cast", IconProperties::new("\uf03d", "#EA8220")),
    (".cbl", IconProperties::new("\u2699", "#005CA5")),
    (".cc", IconProperties::new("\ue61d", "#0188D1")),
    (".ccm", IconProperties::new("\ue61d", "#F34B7D")),
    (".cfg", IconProperties::new("\uf013", "#42A5F5")),
    (".cjs", IconProperties::new("\ue60c", "#CBCB41")),
    (".class", IconProperties::new("\uf0f4", "#2088E5")),
    (".clj", IconProperties::new("\ue642", "#2AB6F6")),
    (".cljc", IconProperties::new("\ue642", "#2AB6F6")),
    (".cljd", IconProperties::new("\ue76a", "#519ABA")),
    (".cljs", IconProperties::new("\ue642", "#2AB6F6")),
    (".cls", IconProperties::new("\ue69b", "#4B5163")),
    (".cmake", IconProperties::new("\ue794", "#DCE3EB")),
    (".cmd", IconProperties::new("\uebc4", "#FF7043")),
    (".cob", IconProperties::new("\u2699", "#005CA5")),
    (".cobol", IconProperties::new("\u2699", "#005CA5")),
    (".coffee", IconProperties::new("\ue61b", "#6F4E38")),
    (".conda", IconProperties::new("\ue715", "#43B02A")),
    (".conf", IconProperties::new("\uf013", "#696969")),
    (".config.ru", IconProperties::new("\ue791", "#701516")),
    (".cp", IconProperties::new("\ue646", "#0188D1")),
    (".cpio", IconProperties::new("\uf410", "#ECA517")),
    (".cpp", IconProperties::new("\ue61d", "#0188D1")),
    (".cppm", IconProperties::new("\ue61d", "#519ABA")),
    (".cpy", IconProperties::new("\u2699", "#005CA5")),
    (".cr", IconProperties::new("\ue62f", "#CFD8DD")),
    (".crdownload", IconProperties::new("\uf019", "#44CDA8")),
    (".cs", IconProperties::new("\u{f031b}", "#0188D1")),
    (".csh", IconProperties::new("\u{f018d}", "#FF7043")),
    (".cshtml", IconProperties::new("\uf486", "#42A5F5")),
    (".cson", IconProperties::new("\ue61b", "#6F4E38")),
    (".csproj", IconProperties::new("\u{f0610}", "#AB48BC")),
    (".css", IconProperties::new("\ue749", "#42A5F5")),
    (".csv", IconProperties::new("\u{f021b}", "#8BC34A")),
    (".csx", IconProperties::new("\u{f031b}", "#0188D1")),
    (".cts", IconProperties::new("\ue628", "#519ABA")),
    (".cu", IconProperties::new("\ue64b", "#89E051")),
    (".cue", IconProperties::new("\u{f0cb9}", "#ED95AE")),
    (".cuh", IconProperties::new("\ue64b", "#A074C4")),
    (".cxx", IconProperties::new("\ue646", "#0188D1")),
    (".cxxm", IconProperties::new("\ue61d", "#519ABA")),
    (".d", IconProperties::new("\ue7af", "#B03931")),
    (".d.ts", IconProperties::new("\ue628", "#0188D1")),
    (".dart", IconProperties::new("\ue64c", "#59B6F0")),
    (".db", IconProperties::new("\uf1c0", "#FFCA29")),
    (".dconf", IconProperties::new("\ue706", "#DAD8D8")),
    (".deb", IconProperties::new("\uebc5", "#D80651")),
    (".desktop", IconProperties::new("\uf108", "#56347C")),
    (".diff", IconProperties::new("\uf4d2", "#4262A2")),
    (".djvu", IconProperties::new("\uf02d", "#624262")),
    (".dll", IconProperties::new("\u{f107c}", "#42A5F5")),
    (".doc", IconProperties::new("\u{f022c}", "#0188D1")),
    (".docx", IconProperties::new("\u{f022c}", "#0188D1")),
    (".dot", IconProperties::new("\u{f1049}", "#005F87")),
    (".download", IconProperties::new("\uf019", "#44CDA8")),
    (".drl", IconProperties::new("\ue28c", "#FFAFAF")),
    (".dropbox", IconProperties::new("\ue707", "#2E63FF")),
    (".ds_store", IconProperties::new("\uf179", "#A2AAAD")),
    (".dump", IconProperties::new("\uf1c0", "#DAD8D8")),
    (".dwg", IconProperties::new("\u{f0eeb}", "#839463")),
    (".dxf", IconProperties::new("\u{f0eeb}", "#839463")),
    (".ebook", IconProperties::new("\ue28b", "#EAB16D")),
    (".ebuild", IconProperties::new("\uf30d", "#4C416E")),
    (".editorconfig", IconProperties::new("\ue615", "#626262")),
    (".edn", IconProperties::new("\ue76a", "#519ABA")),
    (".eex", IconProperties::new("\ue62d", "#9575CE")),
    (".ejs", IconProperties::new("\ue618", "#CBCB41")),
    (".el", IconProperties::new("\ue632", "#805EB7")),
    (".elc", IconProperties::new("\ue632", "#805EB7")),
    (".elf", IconProperties::new("\ueae8", "#9F0500")),
    (".elm", IconProperties::new("\ue62c", "#60B6CC")),
    (".eln", IconProperties::new("\ue632", "#8172BE")),
    (".env", IconProperties::new("\uf462", "#FAF743")),
    (".eot", IconProperties::new("\ue659", "#F54436")),
    (".epp", IconProperties::new("\ue631", "#FFA61A")),
    (".epub", IconProperties::new("\ue28b", "#EAB16D")),
    (".erb", IconProperties::new("\u{f0d2d}", "#F54436")),
    (".erl", IconProperties::new("\uf23f", "#F54436")),
    (".ex", IconProperties::new("\ue62d", "#9575CE")),
    (".exe", IconProperties::new("\uf2d0", "#E64A19")),
    (".exs", IconProperties::new("\ue62d", "#9575CE")),
    (".f#", IconProperties::new("\ue7a7", "#519ABA")),
    (".f3d", IconProperties::new("\u{f0eeb}", "#839463")),
    (".f90", IconProperties::new("\u{f121a}", "#FF7043")),
    (".fbx", IconProperties::new("\uea8c", "#2AB6F6")),
    (".fcbak", IconProperties::new("\uf336", "#6D8086")),
    (".fcmacro", IconProperties::new("\uf336", "#CB333B")),
    (".fcmat", IconProperties::new("\uf336", "#CB333B")),
    (".fcparam", IconProperties::new("\uf336", "#CB333B")),
    (".fcscript", IconProperties::new("\uf336", "#CB333B")),
    (".fcstd", IconProperties::new("\uf336", "#CB333B")),
    (".fcstd1", IconProperties::new("\uf336", "#CB333B")),
    (".fctb", IconProperties::new("\uf336", "#CB333B")),
    (".fctl", IconProperties::new("\uf336", "#CB333B")),
    (".fdmdownload", IconProperties::new("\uf019", "#44CDA8")),
    (".fish", IconProperties::new("\u{f023a}", "#FF7043")),
    (".flac", IconProperties::new("\u{f0386}", "#EE534F")),
    (".flc", IconProperties::new("\uf031", "#ECECEC")),
    (".flf", IconProperties::new("\uf031", "#ECECEC")),
    (".flv", IconProperties::new("\u{f0381}", "#FF9800")),
    (".fnl", IconProperties::new("\ue6af", "#FFF3D7")),
    (".fodg", IconProperties::new("\uf379", "#FFFB57")),
    (".fodp", IconProperties::new("\uf37a", "#FE9C45")),
    (".fods", IconProperties::new("\uf378", "#78FC4E")),
    (".fodt", IconProperties::new("\uf37c", "#2DCBFD")),
    (".font", IconProperties::new("\ue659", "#F54436")),
    (".fs", IconProperties::new("\ue7a7", "#31B9DB")),
    (".fsi", IconProperties::new("\ue7a7", "#31B9DB")),
    (".fsscript", IconProperties::new("\ue7a7", "#519ABA")),
    (".fsx", IconProperties::new("\ue7a7", "#31B9DB")),
    (".gcode", IconProperties::new("\u{f0af4}", "#505075")),
    (".gd", IconProperties::new("\ue65f", "#42A5F5")),
    (".gdoc", IconProperties::new("\uf1c2", "#01D000")),
    (".gem", IconProperties::new("\ue21e", "#C90F02")),
    (".gemfile", IconProperties::new("\ueb48", "#E63936")),
    (".gemspec", IconProperties::new("\ue21e", "#C90F02")),
    (".gform", IconProperties::new("\uf298", "#01D000")),
    (".gif", IconProperties::new("\u{f021f}", "#25A6A0")),
    (".git", IconProperties::new("\u{f02a2}", "#EC6B23")),
    (".glb", IconProperties::new("\uf1b2", "#FFA61A")),
    (".gnumakefile", IconProperties::new("\ueba2", "#EF5351")),
    (".go", IconProperties::new("\ue627", "#02ACC1")),
    (".godot", IconProperties::new("\ue65f", "#42A5F5")),
    (".gpr", IconProperties::new("\ue6b5", "#22FFFF")),
    (".gql", IconProperties::new("\u{f0877}", "#EC417A")),
    (".gradle", IconProperties::new("\ue660", "#0397A7")),
    (".graphql", IconProperties::new("\u{f0877}", "#EC417A")),
    (".gresource", IconProperties::new("\uf362", "#FFFFFF")),
    (".groovy", IconProperties::new("\ue775", "#005F87")),
    (".gsheet", IconProperties::new("\uf1c3", "#97BA6A")),
    (".gslides", IconProperties::new("\uf1c4", "#FFFF00")),
    (".guardfile", IconProperties::new("\ue21e", "#626262")),
    (".gv", IconProperties::new("\u{f1049}", "#005F87")),
    (".gz", IconProperties::new("\uf410", "#ECA517")),
    (".h", IconProperties::new("\uf0fd", "#A074C4")),
    (".haml", IconProperties::new("\ue664", "#F4521E")),
    (".hbs", IconProperties::new("\u{f15de}", "#FF7043")),
    (".hc", IconProperties::new("\u{f00a2}", "#FAF743")),
    (".heex", IconProperties::new("\ue62d", "#9575CE")),
    (".hex", IconProperties::new("\u{f12a7}", "#25A79A")),
    (".hh", IconProperties::new("\uf0fd", "#A074C4")),
    (".hpp", IconProperties::new("\uf0fd", "#A074C4")),
    (".hrl", IconProperties::new("\ue7b1", "#B83998")),
    (".hs", IconProperties::new("\ue61f", "#FFA726")),
    (".htm", IconProperties::new("\uf13b", "#E44E27")),
    (".html", IconProperties::new("\uf13b", "#E44E27")),
    (".huff", IconProperties::new("\u{f0858}", "#CFD8DD")),
    (".hurl", IconProperties::new("\uf0ec", "#FF0288")),
    (".hx", IconProperties::new("\ue666", "#F68713")),
    (".hxx", IconProperties::new("\uf0fd", "#A074C4")),
    (".ical", IconProperties::new("\uf073", "#2B9EF3")),
    (".icalendar", IconProperties::new("\uf073", "#2B9EF3")),
    (".ico", IconProperties::new("\u{f021f}", "#25A6A0")),
    (".ics", IconProperties::new("\u{f01ee}", "#42A5F5")),
    (".ifb", IconProperties::new("\uf073", "#2B9EF3")),
    (".ifc", IconProperties::new("\u{f0eeb}", "#839463")),
    (".ige", IconProperties::new("\u{f0eeb}", "#839463")),
    (".iges", IconProperties::new("\u{f0eeb}", "#839463")),
    (".igs", IconProperties::new("\u{f0eeb}", "#839463")),
    (".image", IconProperties::new("\uf1c5", "#CBCB41")),
    (".img", IconProperties::new("\u{f021f}", "#25A6A0")),
    (".iml", IconProperties::new("\u{f022e}", "#8BC34A")),
    (".import", IconProperties::new("\uf0c6", "#ECECEC")),
    (".info", IconProperties::new("\uf129", "#FFF3D7")),
    (".ini", IconProperties::new("\uf013", "#42A5F5")),
    (".ino", IconProperties::new("\uf34b", "#01979D")),
    (".ipynb", IconProperties::new("\ue80f", "#F57D01")),
    (".iso", IconProperties::new("\uede9", "#B1BEC5")),
    (".ixx", IconProperties::new("\ue61d", "#519ABA")),
    (".j2c", IconProperties::new("\uf1c5", "#4B5163")),
    (".j2k", IconProperties::new("\uf1c5", "#4B5163")),
    (".jad", IconProperties::new("\ue256", "#F19210")),
    (".jar", IconProperties::new("\u{f06ca}", "#F19210")),
    (".java", IconProperties::new("\uf0f4", "#F19210")),
    (".jfi", IconProperties::new("\uf1c5", "#626262")),
    (".jfif", IconProperties::new("\u{f021f}", "#25A6A0")),
    (".jif", IconProperties::new("\uf1c5", "#626262")),
    (".jl", IconProperties::new("\ue624", "#338A23")),
    (".jmd", IconProperties::new("\uf48a", "#519ABA")),
    (".jp2", IconProperties::new("\uf1c5", "#626262")),
    (".jpe", IconProperties::new("\uf1c5", "#626262")),
    (".jpeg", IconProperties::new("\u{f021f}", "#25A6A0")),
    (".jpg", IconProperties::new("\u{f021f}", "#25A6A0")),
    (".jpx", IconProperties::new("\uf1c5", "#626262")),
    (".js", IconProperties::new("\u{f031e}", "#FFCA29")),
    (".json", IconProperties::new("\ue60b", "#FAA825")),
    (".json5", IconProperties::new("\ue60b", "#FAA825")),
    (".jsonc", IconProperties::new("\ue60b", "#FAA825")),
    (".jsx", IconProperties::new("\ued46", "#FFCA29")),
    (".jwmrc", IconProperties::new("\uf35b", "#007AC2")),
    (".jxl", IconProperties::new("\uf1c5", "#727252")),
    (".kbx", IconProperties::new("\u{f0bc4}", "#537662")),
    (".kdb", IconProperties::new("\uf23e", "#529B34")),
    (".kdbx", IconProperties::new("\uf23e", "#529B34")),
    (".kdenlive", IconProperties::new("\uf33c", "#83B8F2")),
    (".kdenlivetitle", IconProperties::new("\uf33c", "#83B8F2")),
    (".kicad_dru", IconProperties::new("\uf34c", "#FFFFFF")),
    (".kicad_mod", IconProperties::new("\uf34c", "#FFFFFF")),
    (".kicad_pcb", IconProperties::new("\uf34c", "#FFFFFF")),
    (".kicad_prl", IconProperties::new("\uf34c", "#FFFFFF")),
    (".kicad_pro", IconProperties::new("\uf34c", "#FFFFFF")),
    (".kicad_sch", IconProperties::new("\uf34c", "#FFFFFF")),
    (".kicad_sym", IconProperties::new("\uf34c", "#FFFFFF")),
    (".kicad_wks", IconProperties::new("\uf34c", "#FFFFFF")),
    (".ko", IconProperties::new("\uf17c", "#DDDDDD")),
    (".kpp", IconProperties::new("\uf33d", "#F245FB")),
    (".kra", IconProperties::new("\uf33d", "#F245FB")),
    (".krz", IconProperties::new("\uf33d", "#F245FB")),
    (".ksh", IconProperties::new("\u{f018d}", "#FF7043")),
    (".kt", IconProperties::new("\ue634", "#1A95D9")),
    (".kts", IconProperties::new("\ue634", "#1A95D9")),
    (".latex", IconProperties::new("\ue69b", "#626262")),
    (".lck", IconProperties::new("\ue672", "#BBBBBB")),
    (".leex", IconProperties::new("\ue62d", "#9575CE")),
    (".less", IconProperties::new("\ued48", "#0277BD")),
    (".lff", IconProperties::new("\uf031", "#ECECEC")),
    (".lhs", IconProperties::new("\ue777", "#A074C4")),
    (".license", IconProperties::new("\u{f0124}", "#FFCA29")),
    (".liquid", IconProperties::new("\uf043", "#2AB6F6")),
    (".localized", IconProperties::new("\uf179", "#A2AAAD")),
    (".lock", IconProperties::new("\uf023", "#FFD550")),
    (".log", IconProperties::new("\uf0f6", "#ECA517")),
    (".lrc", IconProperties::new("\u{f0a16}", "#FFA61A")),
    (".lua", IconProperties::new("\ue620", "#42A5F5")),
    (".luac", IconProperties::new("\ue620", "#519ABA")),
    (".luau", IconProperties::new("\ue620", "#519ABA")),
    (".lz", IconProperties::new("\uf410", "#ECA517")),
    (".lz4", IconProperties::new("\uf410", "#ECA517")),
    (".lzh", IconProperties::new("\uf410", "#ECA517")),
    (".lzma", IconProperties::new("\uf410", "#ECA517")),
    (".lzo", IconProperties::new("\uf410", "#ECA517")),
    (".m", IconProperties::new("\ue61e", "#599EFF")),
    (".m3u", IconProperties::new("\u{f0cb9}", "#ED95AE")),
    (".m3u8", IconProperties::new("\u{f0cb9}", "#ED95AE")),
    (".m4a", IconProperties::new("\u{f0386}", "#EE534F")),
    (".m4v", IconProperties::new("\u{f0381}", "#FF9800")),
    (".magnet", IconProperties::new("\uf076", "#9F0500")),
    (".makefile", IconProperties::new("\ue673", "#FEFEFE")),
    (".markdown", IconProperties::new("\ueb1d", "#42A5F5")),
    (".material", IconProperties::new("\u{f0509}", "#B83998")),
    (".md", IconProperties::new("\ueb1d", "#42A5F5")),
    (".md5", IconProperties::new("\u{f0565}", "#8C86AF")),
    (".mdx", IconProperties::new("\ueb1d", "#FFCA29")),
    (".mint", IconProperties::new("\ue7a4", "#44A047")),
    (".mjs", IconProperties::new("\u{f031e}", "#FFCA29")),
    (".mk", IconProperties::new("\ue795", "#626262")),
    (".mkd", IconProperties::new("\uf48a", "#519ABA")),
    (".mkv", IconProperties::new("\u{f0381}", "#FF9800")),
    (".ml", IconProperties::new("\ue67a", "#FF9800")),
    (".mli", IconProperties::new("\ue67a", "#FF9800")),
    (".mm", IconProperties::new("\ue61d", "#599EFF")),
    (".mo", IconProperties::new("\u{f05ca}", "#7986CB")),
    (".mobi", IconProperties::new("\ue28b", "#EAB16D")),
    (".mojo", IconProperties::new("\ue780", "#FF7043")),
    (".mov", IconProperties::new("\u{f0381}", "#FF9800")),
    (".mp3", IconProperties::new("\u{f0386}", "#EE534F")),
    (".mp4", IconProperties::new("\u{f0381}", "#FF9800")),
    (".mpp", IconProperties::new("\ue61d", "#519ABA")),
    (".msf", IconProperties::new("\uf370", "#137BE1")),
    (".msi", IconProperties::new("\uf2d0", "#E64A19")),
    (".mts", IconProperties::new("\ue628", "#519ABA")),
    (".mustache", IconProperties::new("\u{f15de}", "#FF7043")),
    (".nfo", IconProperties::new("\uf129", "#FFF3D7")),
    (".nim", IconProperties::new("\ue677", "#FFCA29")),
    (".nix", IconProperties::new("\uf313", "#5175C2")),
    (".node", IconProperties::new("\u{f0399}", "#E8274B")),
    (".npmignore", IconProperties::new("\ue71e", "#E8274B")),
    (".nswag", IconProperties::new("\ue60b", "#85EA2D")),
    (".nu", IconProperties::new("\u{f018d}", "#FF7043")),
    (".o", IconProperties::new("\uea8c", "#2AB6F6")),
    (".obj", IconProperties::new("\uea8c", "#2AB6F6")),
    (".odin", IconProperties::new("\u{f07e2}", "#3882D2")),
    (".odf", IconProperties::new("\uf37b", "#FF5A96")),
    (".odg", IconProperties::new("\uf379", "#FFFB57")),
    (".odp", IconProperties::new("\uf37a", "#FE9C45")),
    (".ods", IconProperties::new("\uf378", "#78FC4E")),
    (".odt", IconProperties::new("\uf37c", "#2DCBFD")),
    (".ogg", IconProperties::new("\u{f0381}", "#FF9800")),
    (".ogv", IconProperties::new("\u{f0381}", "#FF9800")),
    (".opus", IconProperties::new("\u{f0223}", "#EA8220")),
    (".org", IconProperties::new("\ue633", "#56B6C2")),
    (".otf", IconProperties::new("\ue659", "#F54436")),
    (".out", IconProperties::new("\ueae8", "#9F0500")),
    (".part", IconProperties::new("\uf43a", "#628262")),
    (".patch", IconProperties::new("\uf440", "#4262A2")),
    (".pck", IconProperties::new("\uf487", "#5D8096")),
    (".pdf", IconProperties::new("\uf1c1", "#EF5351")),
    (".php", IconProperties::new("\u{f031f}", "#2088E5")),
    (".pl", IconProperties::new("\u{f03d2}", "#EF5351")),
    (".pls", IconProperties::new("\u{f0cb9}", "#ED95AE")),
    (".ply", IconProperties::new("\u{f01a7}", "#888888")),
    (".pm", IconProperties::new("\ue769", "#9575CE")),
    (".png", IconProperties::new("\u{f021f}", "#25A6A0")),
    (".po", IconProperties::new("\u{f05ca}", "#7986CB")),
    (".pot", IconProperties::new("\u{f05ca}", "#7986CB")),
    (".pp", IconProperties::new("\ue631", "#FFA61A")),
    (".ppt", IconProperties::new("\u{f0227}", "#D14525")),
    (".pptx", IconProperties::new("\u{f0227}", "#D14525")),
    (".prisma", IconProperties::new("\ue684", "#00BFA5")),
    (".pro", IconProperties::new("\u{f03d2}", "#EF5351")),
    (".procfile", IconProperties::new("\ue607", "#6964BA")),
    (".properties", IconProperties::new("\uf013", "#42A5F5")),
    (".ps1", IconProperties::new("\u{f0a0a}", "#04A9F4")),
    (".psb", IconProperties::new("\u{f021f}", "#25A6A0")),
    (".psd", IconProperties::new("\ue7b8", "#25A6A0")),
    (".psd1", IconProperties::new("\u{f0a0a}", "#04A9F4")),
    (".psm1", IconProperties::new("\u{f0a0a}", "#04A9F4")),
    (".pub", IconProperties::new("\u{f0306}", "#25A79A")),
    (".pxd", IconProperties::new("\ue606", "#00AFFF")),
    (".pxi", IconProperties::new("\ue606", "#00AFFF")),
    (".pxm", IconProperties::new("\uf1c5", "#626262")),
    (".py", IconProperties::new("\ued1b", "#FED836")),
    (".pyc", IconProperties::new("\ue606", "#FFA61A")),
    (".pyd", IconProperties::new("\ue606", "#E3C58E")),
    (".pyi", IconProperties::new("\ue606", "#FFA61A")),
    (".pyo", IconProperties::new("\ue606", "#E3C58E")),
    (".pyw", IconProperties::new("\ue606", "#00AFFF")),
    (".pyx", IconProperties::new("\ue606", "#00AFFF")),
    (".qm", IconProperties::new("\u{f05ca}", "#2596BE")),
    (".qml", IconProperties::new("\uf375", "#42CD52")),
    (".qrc", IconProperties::new("\uf375", "#40CD52")),
    (".qss", IconProperties::new("\uf375", "#40CD52")),
    (".query", IconProperties::new("\ue21c", "#90A850")),
    (".r", IconProperties::new("\ue68a", "#1976D3")),
    (".rake", IconProperties::new("\ue791", "#701516")),
    (".rakefile", IconProperties::new("\ue21e", "#C90F02")),
    (".rar", IconProperties::new("\uf410", "#ECA517")),
    (".razor", IconProperties::new("\uf1fa", "#207245")),
    (".rb", IconProperties::new("\u{f0d2d}", "#F54436")),
    (".rdata", IconProperties::new("\uf25d", "#458EE6")),
    (".rdb", IconProperties::new("\ue76d", "#C90F02")),
    (".rdoc", IconProperties::new("\uf48a", "#519ABA")),
    (".rds", IconProperties::new("\uf25d", "#458EE6")),
    (".readme", IconProperties::new("\uf05a", "#42A5F5")),
    (".res", IconProperties::new("\ue688", "#EF5351")),
    (".resi", IconProperties::new("\ue688", "#FFB300")),
    (".rlib", IconProperties::new("\ue7a8", "#DEA584")),
    (".rmd", IconProperties::new("\ue68a", "#1976D3")),
    (".rpm", IconProperties::new("\ue7bb", "#EE0000")),
    (".rproj", IconProperties::new("\u{f05c6}", "#358A5B")),
    (".rs", IconProperties::new("\ue68b", "#FF7043")),
    (".rspec", IconProperties::new("\ue21e", "#C90F02")),
    (".rspec_parallel", IconProperties::new("\ue21e", "#C90F02")),
    (".rspec_status", IconProperties::new("\ue21e", "#C90F02")),
    (".rss", IconProperties::new("\uf09e", "#965824")),
    (".rtf", IconProperties::new("\u{f022c}", "#0188D1")),
    (".ru", IconProperties::new("\ue21e", "#C90F02")),
    (".rubydoc", IconProperties::new("\ue73b", "#C90F02")),
    (".s", IconProperties::new("\ue637", "#0091BD")),
    (".sass", IconProperties::new("\ue603", "#EC417A")),
    (".sbt", IconProperties::new("\ue68d", "#0277BD")),
    (".sc", IconProperties::new("\ue68e", "#F54436")),
    (".scad", IconProperties::new("\uf34e", "#F9D72C")),
    (".scala", IconProperties::new("\ue68e", "#F54436")),
    (".scm", IconProperties::new("\u{f0627}", "#F54436")),
    (".scss", IconProperties::new("\ue603", "#EC417A")),
    (".sh", IconProperties::new("\u{f018d}", "#FF7043")),
    (".sha1", IconProperties::new("\u{f0565}", "#8C86AF")),
    (".sha224", IconProperties::new("\u{f0565}", "#8C86AF")),
    (".sha256", IconProperties::new("\u{f0565}", "#8C86AF")),
    (".sha384", IconProperties::new("\u{f0565}", "#8C86AF")),
    (".sha512", IconProperties::new("\u{f0565}", "#8C86AF")),
    (".shell", IconProperties::new("\ue795", "#89E051")),
    (".sig", IconProperties::new("\u03bb", "#DC682E")),
    (".signature", IconProperties::new("\u03bb", "#DC682E")),
    (".skp", IconProperties::new("\uea8c", "#2AB6F6")),
    (".sldasm", IconProperties::new("\u{f0eeb}", "#839463")),
    (".sldprt", IconProperties::new("\u{f0eeb}", "#839463")),
    (".slim", IconProperties::new("\ue692", "#F57F19")),
    (".sln", IconProperties::new("\u{f0610}", "#AB48BC")),
    (".slvs", IconProperties::new("\u{f0eeb}", "#839463")),
    (".sml", IconProperties::new("\u03bb", "#DC682E")),
    (".so", IconProperties::new("\u{f107c}", "#42A5F5")),
    (".sol", IconProperties::new("\ue656", "#0188D1")),
    (".spec.js", IconProperties::new("\uf499", "#FFCA29")),
    (".spec.jsx", IconProperties::new("\uf499", "#FFCA29")),
    (".spec.ts", IconProperties::new("\uf499", "#519ABA")),
    (".spec.tsx", IconProperties::new("\uf499", "#0188D1")),
    (".sql", IconProperties::new("\uf1c0", "#CFCA99")),
    (".sqlite", IconProperties::new("\uf1c0", "#CFCA99")),
    (".sqlite3", IconProperties::new("\uf1c0", "#CFCA99")),
    (".srt", IconProperties::new("\u{f0a16}", "#FFA61A")),
    (".ssa", IconProperties::new("\u{f0a16}", "#FFA61A")),
    (".ste", IconProperties::new("\u{f0eeb}", "#839463")),
    (".step", IconProperties::new("\u{f0eeb}", "#839463")),
    (".stl", IconProperties::new("\uea8c", "#2AB6F6")),
    (".stp", IconProperties::new("\uea8c", "#2AB6F6")),
    (".strings", IconProperties::new("\u{f05ca}", "#2596BE")),
    (".sty", IconProperties::new("\ue69b", "#42A5F5")),
    (".styl", IconProperties::new("\ue759", "#C0CA33")),
    (".stylus", IconProperties::new("\ue600", "#83C837")),
    (".sub", IconProperties::new("\u{f0a16}", "#FFA61A")),
    (".sublime", IconProperties::new("\ue7aa", "#DC682E")),
    (".suo", IconProperties::new("\u{f0610}", "#AB48BC")),
    (".sv", IconProperties::new("\u{f035b}", "#FF7043")),
    (".svelte", IconProperties::new("\ue697", "#FF5821")),
    (".svg", IconProperties::new("\u{f0721}", "#FFB300")),
    (".svh", IconProperties::new("\u{f035b}", "#FF7043")),
    (".swift", IconProperties::new("\u{f06e5}", "#FE5E2F")),
    (".t", IconProperties::new("\ue769", "#519ABA")),
    (".tar", IconProperties::new("\uf410", "#ECA517")),
    (".taz", IconProperties::new("\uf410", "#ECA517")),
    (".tbc", IconProperties::new("\u{f06d3}", "#005CA5")),
    (".tbz", IconProperties::new("\uf410", "#ECA517")),
    (".tbz2", IconProperties::new("\uf410", "#ECA517")),
    (".tcl", IconProperties::new("\u{f06d3}", "#EF5351")),
    (".templ", IconProperties::new("\u{f05c0}", "#FFD550")),
    (".terminal", IconProperties::new("\uf489", "#14BA19")),
    (".test.js", IconProperties::new("\uf499", "#FFCA29")),
    (".test.jsx", IconProperties::new("\uf499", "#FFCA29")),
    (".test.ts", IconProperties::new("\uf499", "#519ABA")),
    (".test.tsx", IconProperties::new("\uf499", "#0188D1")),
    (".tex", IconProperties::new("\ue69b", "#42A5F5")),
    (".tf", IconProperties::new("\ue69a", "#5D6BC0")),
    (".tfvars", IconProperties::new("\ue69a", "#5D6BC0")),
    (".tgz", IconProperties::new("\uf410", "#ECA517")),
    (".tiff", IconProperties::new("\u{f021f}", "#25A6A0")),
    (".tlz", IconProperties::new("\uf410", "#ECA517")),
    (".tmux", IconProperties::new("\uebc8", "#14BA19")),
    (".toml", IconProperties::new("\ue6b2", "#9C4221")),
    (".torrent", IconProperties::new("\ue275", "#4C90E8")),
    (".tres", IconProperties::new("\ue65f", "#42A5F5")),
    (".ts", IconProperties::new("\u{f06e6}", "#0188D1")),
    (".tscn", IconProperties::new("\ue65f", "#42A5F5")),
    (".tsconfig", IconProperties::new("\ue772", "#EA8220")),
    (".tsv", IconProperties::new("\u{f021b}", "#8BC34A")),
    (".tsx", IconProperties::new("\ued46", "#04BCD4")),
    (".ttf", IconProperties::new("\ue659", "#F54436")),
    (".twig", IconProperties::new("\ue61c", "#9BB92F")),
    (".txt", IconProperties::new("\u{f0219}", "#42A5F5")),
    (".txz", IconProperties::new("\uf410", "#ECA517")),
    (".typ", IconProperties::new("\uf37f", "#0DBCC0")),
    (".typoscript", IconProperties::new("\ue772", "#EA8220")),
    (".tz", IconProperties::new("\uf410", "#ECA517")),
    (".tzo", IconProperties::new("\uf410", "#ECA517")),
    (".ui", IconProperties::new("\uf2d0", "#015BF0")),
    (".v", IconProperties::new("\ue6ac", "#009CE5")),
    (".vala", IconProperties::new("\ue8d1", "#7B3DB9")),
    (".vh", IconProperties::new("\u{f035b}", "#009900")),
    (".vhd", IconProperties::new("\u{f035b}", "#FF7043")),
    (".vhdl", IconProperties::new("\u{f035b}", "#009900")),
    (".video", IconProperties::new("\uf03d", "#626262")),
    (".vi", IconProperties::new("\ue81e", "#FEC60A")),
    (".vim", IconProperties::new("\ue62b", "#44A047")),
    (".vsh", IconProperties::new("\ue6ac", "#5D87BF")),
    (".vsix", IconProperties::new("\u{f0a1e}", "#2296F3")),
    (".vue", IconProperties::new("\ue6a0", "#40B883")),
    (".war", IconProperties::new("\ue256", "#F54436")),
    (".wasm", IconProperties::new("\ue6a1", "#7D4DFF")),
    (".wav", IconProperties::new("\u{f0386}", "#76B900")),
    (".webm", IconProperties::new("\u{f0381}", "#FF9800")),
    (".webmanifest", IconProperties::new("\ue60b", "#CBCB41")),
    (".webp", IconProperties::new("\u{f021f}", "#25A6A0")),
    (".webpack", IconProperties::new("\u{f072b}", "#519ABA")),
    (".windows", IconProperties::new("\uf17a", "#00A4EF")),
    (".wma", IconProperties::new("\u{f0386}", "#EE534F")),
    (".woff", IconProperties::new("\ue659", "#F54436")),
    (".woff2", IconProperties::new("\ue659", "#F54436")),
    (".wrl", IconProperties::new("\u{f01a7}", "#778899")),
    (".wrz", IconProperties::new("\u{f01a7}", "#778899")),
    (".wv", IconProperties::new("\uf001", "#00AFFF")),
    (".wvc", IconProperties::new("\uf001", "#00AFFF")),
    (".x", IconProperties::new("\ue691", "#599EFF")),
    (".xaml", IconProperties::new("\u{f0673}", "#42A5F5")),
    (".xcf", IconProperties::new("\uf338", "#635b46")),
    (".xcplayground", IconProperties::new("\ue755", "#DC682E")),
    (".xcstrings", IconProperties::new("\u{f05ca}", "#2596BE")),
    (".xhtml", IconProperties::new("\uf13b", "#E44E27")),
    (".xls", IconProperties::new("\u{f021b}", "#8BC34A")),
    (".xlsx", IconProperties::new("\u{f021b}", "#8BC34A")),
    (".xm", IconProperties::new("\ue691", "#519ABA")),
    (".xml", IconProperties::new("\u{f022e}", "#8BC34A")),
    (".xpi", IconProperties::new("\ueae6", "#375A8E")),
    (".xul", IconProperties::new("\uf121", "#DC682E")),
    (".xz", IconProperties::new("\uf410", "#ECA517")),
    (".yaml", IconProperties::new("\ue6a8", "#a074b3")),
    (".yml", IconProperties::new("\ue6a8", "#a074b3")),
    (".zig", IconProperties::new("\ue6a9", "#FAA825")),
    (".zip", IconProperties::new("\uf410", "#ECA517")),
    (".zsh", IconProperties::new("\u{f018d}", "#FF7043")),
    (".zsh-theme", IconProperties::new("\ue795", "#89E051")),
    (".zshrc", IconProperties::new("\ue795", "#89E051")),
    (".zst", IconProperties::new("\uf410", "#ECA517")),
];

static EXT_ICON_MAP_V2: &[(&str, IconProperties)] = &[
    (".cs", IconProperties::new("\uf81a", "#FEDECA")),
    (".csproj", IconProperties::new("\uf81a", "#AB48BC")),
    (".csx", IconProperties::new("\uf81a", "#0188D1")),
    (".license", IconProperties::new("\uf718", "#626262")),
    (".node", IconProperties::new("\uf898", "#E8274B")),
    (".rtf", IconProperties::new("\uf718", "#626262")),
    (".vue", IconProperties::new("\ufd42", "#89e051")),
];

lazy_static! {
    static ref NAME_ICON_MAP_HASH: HashMap<&'static str, IconProperties> = {
        NAME_ICON_MAP.iter().cloned().collect()
    };
    static ref EXT_ICON_MAP_HASH: HashMap<&'static str, IconProperties> = {
        EXT_ICON_MAP.iter().cloned().collect()
    };
    static ref EXT_ICON_MAP_V2_HASH: HashMap<&'static str, IconProperties> = {
        let mut m = HashMap::new();
        for (k, v) in EXT_ICON_MAP_V2.iter() {
            m.insert(*k, *v);
        }
        m
    };
}

pub fn default_file_icon() -> IconProperties {
    DEFAULT_FILE_ICON
}

pub fn default_submodule_icon() -> IconProperties {
    DEFAULT_SUBMODULE_ICON
}

pub fn default_directory_icon() -> IconProperties {
    DEFAULT_DIRECTORY_ICON
}

pub fn patch_for_nerd_fonts_v2() {
    for (k, v) in EXT_ICON_MAP_V2 {
        EXT_ICON_MAP_HASH.write().unwrap().insert(k, *v);
    }
}

pub fn icon_for_file(
    path: &Path,
    is_submodule: bool,
    is_linked_worktree: bool,
    is_directory: bool,
    _custom_icons_filenames: Option<&HashMap<String, IconProperties>>,
    _custom_icons_extensions: Option<&HashMap<String, IconProperties>>,
) -> IconProperties {
    if let Some(base) = path.file_name().and_then(|n| n.to_str()) {
        if let Some(custom) = _custom_icons_filenames {
            if let Some(icon) = custom.get(base) {
                return *icon;
            }
        }
        if let Some(icon) = NAME_ICON_MAP_HASH.read().unwrap().get(base) {
            return *icon;
        }
    }

    if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
        let ext_lower = format!(".{}", ext.to_lowercase());
        if let Some(custom) = _custom_icons_extensions {
            if let Some(icon) = custom.get(&ext_lower) {
                return *icon;
            }
        }
        if let Some(icon) = EXT_ICON_MAP_HASH.read().unwrap().get(ext_lower.as_str()) {
            return *icon;
        }
    }

    if is_submodule {
        DEFAULT_SUBMODULE_ICON
    } else if is_linked_worktree {
        IconProperties::new("\u{f0339}", "#4E4E4E")
    } else if is_directory {
        DEFAULT_DIRECTORY_ICON
    } else {
        DEFAULT_FILE_ICON
    }
}
