use serde::{Deserialize, Serialize};

use crate::state::{InputPromptOperation, ModalKind, RepoId, RepoSubview};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Action {
    EnterRepoMode { repo_id: RepoId },
    LeaveRepoMode,
    SelectNextRepo,
    SelectPreviousRepo,
    FocusWorkspaceSearch,
    BlurWorkspaceSearch,
    CancelWorkspaceSearch,
    AppendWorkspaceSearch { text: String },
    BackspaceWorkspaceSearch,
    CycleWorkspaceFilter,
    CycleWorkspaceSort,
    SelectNextStatusEntry,
    SelectPreviousStatusEntry,
    SelectNextBranch,
    SelectPreviousBranch,
    SelectNextCommit,
    SelectPreviousCommit,
    ScrollRepoDetailUp,
    ScrollRepoDetailDown,
    SelectNextDiffHunk,
    SelectPreviousDiffHunk,
    SetFocusedPane(crate::state::PaneId),
    OpenModal { kind: ModalKind, title: String },
    CloseTopModal,
    ConfirmPendingOperation,
    OpenInputPrompt { operation: InputPromptOperation },
    AppendPromptInput { text: String },
    BackspacePromptInput,
    SubmitPromptInput,
    RefreshSelectedRepo,
    RefreshVisibleRepos,
    StageSelection,
    StageSelectedFile,
    UnstageSelectedFile,
    StageSelectedHunk,
    UnstageSelectedHunk,
    OpenCommitBox { mode: crate::state::CommitBoxMode },
    CancelCommitBox,
    AppendCommitInput { text: String },
    BackspaceCommitInput,
    SubmitCommitBox,
    CommitStaged { message: String },
    AmendHead { message: Option<String> },
    CheckoutSelectedBranch,
    CheckoutBranch { branch_ref: String },
    DeleteSelectedBranch,
    FetchSelectedRepo,
    PullCurrentBranch,
    PushCurrentBranch,
    SwitchRepoSubview(RepoSubview),
    ApplyWorkspaceScan(crate::state::WorkspaceState),
}
