use serde::{Deserialize, Serialize};

use crate::state::{InputPromptOperation, ModalKind, RepoId, RepoSubview};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Action {
    EnterRepoMode { repo_id: RepoId },
    LeaveRepoMode,
    SelectNextRepo,
    SelectPreviousRepo,
    FocusWorkspaceSearch,
    BlurWorkspaceSearch,
    CancelWorkspaceSearch,
    AppendWorkspaceSearch { text: String },
    BackspaceWorkspaceSearch,
    CycleWorkspaceFilter,
    CycleWorkspaceSort,
    SelectNextStatusEntry,
    SelectPreviousStatusEntry,
    SelectNextBranch,
    SelectPreviousBranch,
    SelectNextCommit,
    SelectPreviousCommit,
    OpenSelectedBranchCommits,
    OpenAllBranchGraph { reverse: bool },
    OpenSelectedCommitFiles,
    CloseSelectedCommitFiles,
    CheckoutSelectedCommit,
    CheckoutSelectedCommitFile,
    CreateBranchFromSelectedCommit,
    StartInteractiveRebase,
    AmendSelectedCommit,
    FixupSelectedCommit,
    RewordSelectedCommit,
    RewordSelectedCommitWithEditor,
    CherryPickSelectedCommit,
    RevertSelectedCommit,
    ContinueRebase,
    AbortRebase,
    SkipRebase,
    SelectNextStash,
    SelectPreviousStash,
    SelectNextReflog,
    SelectPreviousReflog,
    RestoreSelectedReflogEntry,
    OpenSelectedReflogCommits,
    SelectNextWorktree,
    SelectPreviousWorktree,
    ToggleComparisonSelection,
    ClearComparison,
    ScrollRepoDetailUp,
    ScrollRepoDetailDown,
    SelectNextDiffHunk,
    SelectPreviousDiffHunk,
    SelectNextDiffLine,
    SelectPreviousDiffLine,
    ToggleDiffLineAnchor,
    SetFocusedPane(crate::state::PaneId),
    OpenModal { kind: ModalKind, title: String },
    CloseTopModal,
    SelectNextMenuItem,
    SelectPreviousMenuItem,
    SubmitMenuSelection,
    ConfirmPendingOperation,
    OpenStashOptions,
    OpenInputPrompt { operation: InputPromptOperation },
    AppendPromptInput { text: String },
    BackspacePromptInput,
    SubmitPromptInput,
    OpenInEditor,
    RefreshSelectedRepo,
    RefreshVisibleRepos,
    StageSelection,
    StageSelectedFile,
    DiscardSelectedFile,
    UnstageSelectedFile,
    StageSelectedHunk,
    UnstageSelectedHunk,
    StageSelectedLines,
    UnstageSelectedLines,
    OpenCommitBox { mode: crate::state::CommitBoxMode },
    CancelCommitBox,
    AppendCommitInput { text: String },
    BackspaceCommitInput,
    SubmitCommitBox,
    CommitStaged { message: String },
    CommitStagedNoVerify { message: String },
    CommitStagedWithEditor,
    AmendHead { message: Option<String> },
    SoftResetToSelectedCommit,
    MixedResetToSelectedCommit,
    HardResetToSelectedCommit,
    NukeWorkingTree,
    CheckoutSelectedBranch,
    CheckoutBranch { branch_ref: String },
    DeleteSelectedBranch,
    StashAllChanges,
    ApplySelectedStash,
    PopSelectedStash,
    DropSelectedStash,
    CreateWorktree,
    RemoveSelectedWorktree,
    FetchSelectedRepo,
    PullCurrentBranch,
    PushCurrentBranch,
    ActivateRepoSubviewSelection,
    FocusRepoMainPane,
    OpenRepoWorktreesSubview,
    FocusRepoSubviewFilter,
    BlurRepoSubviewFilter,
    CancelRepoSubviewFilter,
    AppendRepoSubviewFilter { text: String },
    BackspaceRepoSubviewFilter,
    SwitchRepoSubview(RepoSubview),
    ApplyWorkspaceScan(crate::state::WorkspaceState),
}
