use serde::{Deserialize, Serialize};

use crate::state::{InputPromptOperation, MergeVariant, ModalKind, RepoId, RepoSubview};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Action {
    EnterRepoMode {
        repo_id: RepoId,
    },
    EnterNestedRepoMode {
        repo_id: RepoId,
        parent_repo_id: RepoId,
    },
    LeaveRepoMode,
    SelectNextRepo,
    SelectPreviousRepo,
    FocusWorkspaceSearch,
    BlurWorkspaceSearch,
    CancelWorkspaceSearch,
    AppendWorkspaceSearch {
        text: String,
    },
    BackspaceWorkspaceSearch,
    CycleWorkspaceFilter,
    CycleWorkspaceSort,
    SelectNextStatusEntry,
    SelectPreviousStatusEntry,
    SelectStatusEntry {
        pane: crate::state::PaneId,
        index: usize,
    },
    SelectNextBranch,
    SelectPreviousBranch,
    SelectNextRemote,
    SelectPreviousRemote,
    SelectNextRemoteBranch,
    SelectPreviousRemoteBranch,
    SelectNextTag,
    SelectPreviousTag,
    SelectNextCommit,
    SelectPreviousCommit,
    PageDownRepoList {
        page_size: usize,
    },
    PageUpRepoList {
        page_size: usize,
    },
    SelectFirstRepoListEntry,
    SelectLastRepoListEntry,
    OpenSelectedBranchCommits,
    OpenSelectedRemoteBranches,
    OpenSelectedRemoteBranchCommits,
    OpenSelectedTagCommits,
    OpenAllBranchGraph {
        reverse: bool,
    },
    OpenSelectedCommitFiles,
    CloseSelectedCommitFiles,
    OpenSelectedStashFiles,
    CloseSelectedStashFiles,
    CheckoutSelectedCommit,
    CheckoutSelectedCommitFile,
    CreateBranchFromSelectedCommit,
    CreateTagFromSelectedCommit,
    CopySelectedCommitHash,
    OpenCommitCopyOptions,
    OpenCommitAmendAttributeOptions,
    OpenSelectedCommitInBrowser,
    OpenBisectOptions,
    StartInteractiveRebase,
    AmendSelectedCommit,
    OpenCommitFixupOptions,
    StartBisectBad,
    StartBisectGood,
    MarkBisectBad,
    MarkBisectGood,
    SkipBisect,
    ResetBisect,
    CreateFixupCommit,
    FixupSelectedCommit,
    SetFixupMessageForSelectedCommit,
    ApplyFixupCommits,
    SquashSelectedCommit,
    DropSelectedCommit,
    MoveSelectedCommitUp,
    MoveSelectedCommitDown,
    RewordSelectedCommit,
    RewordSelectedCommitWithEditor,
    CopySelectedCommitForCherryPick,
    CherryPickCopiedCommit,
    ClearCopiedCommitSelection,
    CherryPickSelectedCommit,
    RevertSelectedCommit,
    ContinueRebase,
    AbortRebase,
    SkipRebase,
    SelectNextStash,
    SelectPreviousStash,
    SelectNextStashFile,
    SelectPreviousStashFile,
    SelectNextReflog,
    SelectPreviousReflog,
    RestoreSelectedReflogEntry,
    OpenSelectedReflogCommits,
    CopySelectedReflogCommitHash,
    OpenSelectedReflogInBrowser,
    OpenReflogResetOptions,
    SelectNextWorktree,
    SelectPreviousWorktree,
    SelectNextSubmodule,
    SelectPreviousSubmodule,
    CopySelectedSubmoduleName,
    OpenSubmoduleOptions,
    InitAllSubmodules,
    UpdateAllSubmodules,
    UpdateAllSubmodulesRecursively,
    DeinitAllSubmodules,
    ToggleComparisonSelection,
    ClearComparison,
    SelectRepoDetailItem {
        index: usize,
    },
    ScrollRepoDetailUp,
    ScrollRepoDetailDown,
    SelectNextDiffHunk,
    SelectPreviousDiffHunk,
    SelectNextDiffLine,
    SelectPreviousDiffLine,
    ToggleDiffLineAnchor,
    SetFocusedPane(crate::state::PaneId),
    OpenModal {
        kind: ModalKind,
        title: String,
    },
    ShowWarning {
        message: String,
    },
    CloseTopModal,
    SelectNextMenuItem,
    SelectPreviousMenuItem,
    SubmitMenuSelection,
    ConfirmPendingOperation,
    OpenStashOptions,
    OpenFilterOptions,
    OpenDiffOptions,
    OpenCommitLogOptions,
    ToggleWhitespaceInDiff,
    IncreaseDiffContext,
    DecreaseDiffContext,
    IncreaseRenameSimilarityThreshold,
    DecreaseRenameSimilarityThreshold,
    OpenMergeRebaseOptions,
    OpenPatchOptions,
    OpenRecentRepos,
    OpenCommandLog,
    NextScreenMode,
    PreviousScreenMode,
    OpenInputPrompt {
        operation: InputPromptOperation,
    },
    AppendPromptInput {
        text: String,
    },
    BackspacePromptInput,
    SubmitPromptInput,
    OpenInEditor,
    OpenConfigFileInDefaultApp,
    OpenConfigFileInEditor,
    CheckForUpdates,
    RefreshSelectedRepo,
    RefreshSelectedRepoDeep,
    RefreshVisibleRepos,
    StageSelection,
    UnstageSelection,
    StageSelectedFile,
    DiscardSelectedFile,
    UnstageSelectedFile,
    ToggleStatusTree,
    CollapseStatusEntry,
    ExpandStatusEntry,
    CycleStatusFilterMode,
    OpenSelectedStatusEntry,
    OpenIgnoreOptions,
    IgnoreSelectedStatusPath,
    ExcludeSelectedStatusPath,
    CopySelectedStatusPath,
    OpenSelectedStatusPathInDefaultApp,
    OpenSelectedStatusPathInExternalDiffTool,
    OpenStatusResetOptions,
    SoftResetToUpstream,
    MixedResetToUpstream,
    HardResetToUpstream,
    StageSelectedHunk,
    UnstageSelectedHunk,
    StageSelectedLines,
    UnstageSelectedLines,
    OpenCommitBox {
        mode: crate::state::CommitBoxMode,
    },
    CancelCommitBox,
    AppendCommitInput {
        text: String,
    },
    BackspaceCommitInput,
    SubmitCommitBox,
    CommitStaged {
        message: String,
    },
    CommitStagedNoVerify {
        message: String,
    },
    CommitStagedWithEditor,
    AmendHead {
        message: Option<String>,
    },
    SoftResetToSelectedCommit,
    MixedResetToSelectedCommit,
    HardResetToSelectedCommit,
    NukeWorkingTree,
    CheckoutSelectedBranch,
    FetchSelectedRemote,
    CheckoutSelectedRemoteBranch,
    CheckoutSelectedTag,
    CheckoutBranch {
        branch_ref: String,
    },
    OpenBranchGitFlowOptions,
    OpenBranchPullRequestOptions,
    OpenBranchResetOptions,
    OpenBranchSortOptions,
    OpenBranchUpstreamOptions,
    OpenRemoteBranchPullRequestOptions,
    OpenRemoteBranchResetOptions,
    OpenRemoteBranchSortOptions,
    CopySelectedBranchName,
    DeleteSelectedBranch,
    ForceCheckoutSelectedBranch,
    UnsetSelectedBranchUpstream,
    FastForwardSelectedBranchFromUpstream,
    MergeSelectedRefIntoCurrent {
        variant: MergeVariant,
    },
    MergeSelectedBranchIntoCurrent,
    RebaseCurrentBranchOntoSelectedBranch,
    OpenSelectedBranchPullRequest,
    CopySelectedBranchPullRequestUrl,
    CreateTagFromSelectedBranch,
    SetBranchSortMode(crate::state::BranchSortMode),
    RunGitFlowFinish,
    DeleteSelectedRemote,
    DeleteSelectedRemoteBranch,
    DeleteSelectedTag,
    PushSelectedTag,
    CopySelectedTagName,
    OpenTagResetOptions,
    CreateLocalBranchFromSelectedRemoteBranch,
    CopySelectedRemoteBranchName,
    SetCurrentBranchUpstreamToSelectedRemoteBranch,
    MergeSelectedRemoteBranchIntoCurrent,
    RebaseCurrentBranchOntoSelectedRemoteBranch,
    OpenSelectedRemoteBranchPullRequest,
    CopySelectedRemoteBranchPullRequestUrl,
    CreateTagFromSelectedRemoteBranch,
    SetRemoteBranchSortMode(crate::state::RemoteBranchSortMode),
    SoftResetToSelectedTag,
    MixedResetToSelectedTag,
    HardResetToSelectedTag,
    StashAllChanges,
    ApplySelectedStash,
    PopSelectedStash,
    DropSelectedStash,
    CreateWorktree,
    RemoveSelectedWorktree,
    CreateSubmodule,
    EditSelectedSubmodule,
    InitSelectedSubmodule,
    UpdateSelectedSubmodule,
    RemoveSelectedSubmodule,
    FetchSelectedRepo,
    PullCurrentBranch,
    PushCurrentBranch,
    ActivateRepoSubviewSelection,
    FocusRepoMainPane,
    OpenRepoWorktreesSubview,
    OpenRepoSubmodulesSubview,
    SelectNextRepoSubview,
    SelectPreviousRepoSubview,
    FocusRepoSubviewFilter,
    BlurRepoSubviewFilter,
    CancelRepoSubviewFilter,
    AppendRepoSubviewFilter {
        text: String,
    },
    BackspaceRepoSubviewFilter,
    SwitchRepoSubview(RepoSubview),
    ApplyWorkspaceScan(crate::state::WorkspaceState),
}
